name: AutoKonachain

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 22 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: Install Requirements
      run: |
        pip3 install setuptools
        pip3 install -r requirements.txt
        
    - name: Run Script
      run: |
        python3 TelegramPusher.py ${{ secrets.BOTID }} ${{ secrets.CHANNELID }}

    - name: Move Files
      run: |
        mkdir Konachan
        mkdir ./Konachan/Konachan-$(date -d +1day +%Y-%m-%d)/
        mv ./pic/* ./Konachan/Konachan-$(date -d +1day +%Y-%m-%d)/
    
    - uses: actions/upload-artifact@v2
      with:
        name: Konachan
        path: ./Konachan/